trigger:
  branches:
    include:
    - master
    - release-*

jobs:
- job:
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-18.04'
        python.version: '3.x'
        CXX: g++
        BUILD_PYTHON_API: ON
        BUILD_SPARK_API: ON
      macOS:
        imageName: 'macOS-10.14'
        python.version: '3.x'
        CXX: clang++

  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - template: ci/azure-linux_mac.yml
