trigger:
  branches:
    include:
    - master
    - release-*
  tags:
    include:
      - "*"

jobs:
- job: Build
  strategy:
    matrix:
      linux:
        imageName: 'ubuntu-18.04'
        python.version: '3.x'
        CXX: g++
        BUILD_PYTHON_API: ON
        BUILD_SPARK_API: ON

  pool:
    vmImage: $(imageName)
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'
      architecture: 'x64'
  - script: printenv
    displayName: 'Print Env'
  - template: ci/azure-linux_mac.yml

